//! A very simple example that interfaces with the blud LED (PF2) and SW2 (PF0) 
//! using direct register access. When SW2 is pressed, the LED is turned on. When 
//! SW2 is released, the LED is turned off. Interrupt on PF0 is configured as 
//! edge-triggered on both edges
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "C:\ti\TivaWare_C_Series-2.1.2.111\examples\boards\ek-tm4c123gxl\switch_delay_interrupt_TivaWare\switch_delay_interrupt_PinMux.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "inc/tm4c123gh6pm.h"	//manually added by the programmer
volatile unsigned long count=0;
//*****************************************************************************

void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
	
    //
    // Enable pin PF2 for GPIOOutput
    //
GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);


		// Enable pin PF1 for GPIOOutput
    //
GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);
		//
	
		//
    // Enable pin PF4 for GPIOInput
    //
GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

	
		//
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);
		
		//*************************************************************
		//	The code above is automatically generated by PinMux
		//  The code below should be manually added by the programmer
		//*************************************************************
		
		//Enable pull-up on PF4 and PF0
		GPIO_PORTF_PUR_R |= 0x11; 
		
}

void
Interrupt_Init(void)
{
IntEnable(INT_GPIOF);  							// enable interrupt 30 in NVIC (GPIOF)
	IntPrioritySet(INT_GPIOF, 0x00); 		// configure GPIOF interrupt priority as 0
	GPIO_PORTF_IM_R |= 0x11;   					// arm interrupt on PF0
	GPIO_PORTF_IS_R &= ~0x11;   			// PF0 is edge-sensitive
	GPIO_PORTF_IBE_R &= ~0x11;   				// PF0 both edges trigger 
  GPIO_PORTF_IEV_R &= ~0x11;  			// PF0 falling edge event
	IntMasterEnable();        					// globally enable interrupt
}

//interrupt handler
void GPIOPortF_Handler(void){
		// Delay for a bit.
				SysCtlDelay(2000000);	
	
  GPIO_PORTF_DATA_R ^= 0x02;
	
	//SW1 is pressed
	if(GPIO_PORTF_RIS_R&0x10)
	{
		//Acknowledge flag for PF4
		GPIOIntClear(GPIO_PORTF_BASE, GPIO_PIN_4); 
		
		//PF1 is on
		if((GPIO_PORTF_DATA_R&0x02)==0x00)
		{
				//Toggle PF2
				GPIO_PORTF_DATA_R ^=0x04;
		}
		//Counter increase by 1
		count++;
	}
	
	//SW2 is pressed
  if(GPIO_PORTF_RIS_R&0x01)
	{
		//Acknowledge flag for PF0
		GPIOIntClear(GPIO_PORTF_BASE, GPIO_PIN_0);
		
		//PF1 is off
		if((GPIO_PORTF_DATA_R&0x02)==0X02)
		{
				//Toggle PF2
				GPIO_PORTF_DATA_R ^=0x04;
		}
		//Counter decrease by 1
		count--;
	}
}



int main(void)
{
	
		//initialize the GPIO ports	
		PortFunctionInit();
	
		//configure the GPIOF interrupt
		Interrupt_Init();
	
    //
    // Loop forever.
    //
while(1)
    {

    }
}
